### ISSUE TITLE
[Suggestion] Bukkit Update Checker

### ISSUE THREAD

**Issue by AverageFemale** [Sal4iDev/sVisualBukkit#8]
Is it possible to add an option to check dev.bukkit.org for updates?

:+1:

**Comment by Sal4iDev** [comment]
> Is it possible to add an option to check dev.bukkit.org for updates?
> 
> :+1:

why? use spigot

**Comment by AverageFemale** [comment]
Because I don't feel like using spigot. :D

If you don't wanna do it, its fine. Feel free to close.
